"""Build Time Actual's vendored mbedTLS archive and generate build/version.h.

Usage (from project root):

    python scripts/build.py

This used to build the native Direct2D `Lunar.exe`. Since 0.50 the product
is the Tcl/Tk shell, built by `kuu.exe run build`, which reuses
the two helpers here: `build_mbedtls_archive()` compiles the vendored
mbedTLS 3.6.6 sources into a hash-cached static archive, and
`write_version_header()` renders `build/version.h` from the top-level
VERSION file. `tests/run_tests.py` imports the same helpers for the C unit
tests. Uses only the compiler installed by `kuu.exe run prereqs`.
"""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path


# ---- paths -----------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
VERSION_FILE = ROOT / "VERSION"
TOOL_BIN = ROOT / ".tools" / "msys2" / "ucrt64" / "bin"

# Vendored mbedTLS 3.6.6 LTS. Produced from an upstream tarball whose
# SHA-256 we checked against the release page before committing the
# source tree (see third_party/lunar_mbedtls_config.h for rationale
# and /memories/session/mbedtls_vendor.md for the audit trail).
MBEDTLS_DIR = ROOT / "third_party" / "mbedtls-3.6.6"
MBEDTLS_CONFIG = ROOT / "third_party" / "lunar_mbedtls_config.h"


def log(msg: str) -> None:
    print(f"==> {msg}", flush=True)


def die(msg: str) -> "None":
    print(f"build.py: {msg}", file=sys.stderr)
    sys.exit(1)


def run(*args: str | os.PathLike) -> None:
    """Run a command, streaming output; die on non-zero exit."""
    cmd = [str(a) for a in args]
    log(" ".join(cmd))
    rc = subprocess.call(cmd)
    if rc != 0:
        die(f"command failed (exit {rc}): {cmd[0]}")


def find_tool(name: str) -> Path:
    """Return a tool from this checkout; never discover another installation."""
    candidate = TOOL_BIN / f"{name}.exe"
    if candidate.is_file():
        return candidate
    die(f"{candidate} is missing; run .\\kuu.exe run prereqs")
    raise SystemExit  # unreachable; keeps type checkers happy


# ---- version single-sourcing -------------------------------------------------
#
# The top-level VERSION file is the single source of truth. This module
# renders build/version.h so C sources can #include "version.h" (the build
# dir is on the app include path); tools/genres.tcl separately forwards the
# same VERSION to windres for the Tk exe's resource/manifest fields.

def read_version() -> str:
    """Return the MAJOR.MINOR version string from the VERSION file.

    Lunar uses a two-part version (like els: 0.50), so the exe's four-part
    Windows resource/manifest fields are this padded with zeros (0.50.0.0).
    """
    try:
        v = VERSION_FILE.read_text(encoding="utf-8").strip()
    except OSError as e:
        die(f"cannot read {VERSION_FILE}: {e}")
    if not re.fullmatch(r"\d+\.\d+", v):
        die(f"VERSION file contains {v!r}; expected MAJOR.MINOR (e.g. 0.50)")
    return v


def write_version_header(build_dir: Path = BUILD,
                         version: str | None = None) -> Path:
    """Generate <build_dir>/version.h from the VERSION file.

    Standalone (no other build state needed) so the Kuu task runner and
    tests/run_tests.py can both reuse it. Only rewrites the file when the
    content changes, to keep mtimes stable for caching.
    """
    if version is None:
        version = read_version()
    parts = [int(p) for p in version.split(".")]
    major, minor = parts[0], parts[1]
    patch = parts[2] if len(parts) > 2 else 0
    build_dir.mkdir(parents=True, exist_ok=True)
    header = build_dir / "version.h"
    text = (
        "/* Generated by scripts/build.py from the top-level VERSION file.\n"
        " * Do not edit by hand; edit VERSION instead. */\n"
        "#ifndef LUNAR_VERSION_H\n"
        "#define LUNAR_VERSION_H\n"
        f'#define LUNAR_VERSION_STR "{version}"\n'
        f"#define LUNAR_VERSION_MAJOR {major}\n"
        f"#define LUNAR_VERSION_MINOR {minor}\n"
        f"#define LUNAR_VERSION_PATCH {patch}\n"
        "#endif /* LUNAR_VERSION_H */\n"
    )
    if not (header.is_file()
            and header.read_text(encoding="utf-8") == text):
        header.write_text(text, encoding="utf-8", newline="\n")
    return header


# ---- mbedTLS vendored build -------------------------------------------------
#
# We compile every .c in third_party/mbedtls-3.6.6/library/ into a static
# archive (libmbedtls_lunar.a) and link it into Lunar. The archive is
# hash-cached: if the config, headers, and sources haven't changed, we
# skip recompilation. First build takes ~30 s; subsequent builds are
# instant.
#
# Security note: our config (third_party/lunar_mbedtls_config.h) disables
# every mbedTLS module Lunar does not need -- the disabled .c files still
# compile, but they compile to nothing because their module-level guards
# are undefined. This is the pattern recommended by the mbedTLS team.

def _mbedtls_cache_key() -> str:
    """Hash every file that affects the mbedTLS library build.

    If ANY of these change -- config, headers, or sources -- the archive
    is invalidated and rebuilt. Cheap to compute (a few MB of SHA-256).
    """
    h = hashlib.sha256()
    # A compiler or recipe change must invalidate the native archive too.
    h.update(Path(__file__).read_bytes())
    h.update((ROOT / "tools" / "prereqs.json").read_bytes())
    h.update(find_tool("gcc").read_bytes())
    inputs = sorted([
        MBEDTLS_CONFIG,
        *(MBEDTLS_DIR / "include").rglob("*.h"),
        *(MBEDTLS_DIR / "library").glob("*.c"),
        *(MBEDTLS_DIR / "library").glob("*.h"),
    ])
    for f in inputs:
        h.update(f.as_posix().encode("utf-8"))
        h.update(b"\0")
        h.update(f.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def build_mbedtls_archive(gcc: Path) -> Path:
    """Return path to libmbedtls_lunar.a, (re)building if stale."""
    key = _mbedtls_cache_key()
    cache_dir = BUILD / "mbedtls" / key
    archive = cache_dir / "libmbedtls_lunar.a"
    stamp = cache_dir / ".ok"
    if stamp.is_file() and archive.is_file():
        log(f"mbedTLS archive cache hit ({key})  -> {archive}")
        return archive

    # Clean any other cache directories -- keep only the current one.
    cache_root = BUILD / "mbedtls"
    if cache_root.is_dir():
        for d in cache_root.iterdir():
            if d.is_dir() and d.name != key:
                shutil.rmtree(d, ignore_errors=True)
    cache_dir.mkdir(parents=True, exist_ok=True)
    obj_dir = cache_dir / "obj"
    obj_dir.mkdir(exist_ok=True)

    log(f"Building mbedTLS 3.6.6 archive ({key})")

    # The MBEDTLS_CONFIG_FILE macro is pasted verbatim into an #include
    # directive inside mbedTLS's build_info.h. We pass it with angle
    # brackets so the preprocessor searches the include path; the file
    # lives in third_party/ which we add with -I below.
    config_flag = "-DMBEDTLS_CONFIG_FILE=<lunar_mbedtls_config.h>"

    includes = [
        f"-I{MBEDTLS_DIR / 'include'}",
        f"-I{MBEDTLS_DIR / 'library'}",
        f"-I{ROOT / 'third_party'}",
    ]

    # -O2 for speed (the TLS handshake dominates each NTP cycle's budget
    # if we're lazy about crypto). -Wall -Wextra so we catch integration
    # warnings. -Wno-unused-function because many mbedTLS helpers compile
    # to unused when their module is disabled -- that's not a bug, it's
    # the whole point of the minimal config.
    common_flags = [
        "-O2", "-g",
        "-Wall", "-Wextra",
        "-Wno-unused-function",
        "-Wno-unused-parameter",
        "-Wno-unused-variable",
        "-Wno-unused-but-set-variable",
        "-std=c11",
        "-DWIN32_LEAN_AND_MEAN",
        "-D_WIN32_WINNT=0x0601",
        config_flag,
    ] + includes

    srcs = sorted((MBEDTLS_DIR / "library").glob("*.c"))

    # Parallel compile -- up to CPU count.
    def compile_one(src: Path) -> tuple[Path, int, str]:
        obj = obj_dir / (src.stem + ".o")
        cmd = [str(gcc), *common_flags, "-c", str(src), "-o", str(obj)]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        return obj, proc.returncode, proc.stderr

    with ThreadPoolExecutor(max_workers=os.cpu_count() or 4) as pool:
        results = list(pool.map(compile_one, srcs))

    failed = [(s, rc, err) for (s, rc, err) in zip(srcs, [r[1] for r in results],
              [r[2] for r in results]) if rc != 0]
    if failed:
        for src, rc, err in failed:
            print(f"---- FAILED: {src.name} (rc {rc}) ----", file=sys.stderr)
            print(err, file=sys.stderr)
        die(f"{len(failed)} mbedTLS file(s) failed to compile")

    # Any non-silent warnings worth flagging? Collect stderr with content.
    for src, (_, _, err) in zip(srcs, results):
        if err.strip():
            # Not fatal -- show once so the human sees them.
            print(f"[mbedtls warn] {src.name}:", file=sys.stderr)
            print(err, file=sys.stderr)

    # Pack into archive.
    ar = find_tool("ar")
    objs = [str(r[0]) for r in results]
    archive.unlink(missing_ok=True)
    # Use @response-file to dodge the Windows 32K cmdline limit -- 100+
    # object paths can overflow in extreme cases.
    rsp = cache_dir / "ar.rsp"
    rsp.write_text(" ".join(f'"{o}"' for o in objs), encoding="utf-8")
    run(ar, "rcs", archive, f"@{rsp}")
    rsp.unlink(missing_ok=True)
    stamp.write_text(key, encoding="utf-8")
    log(f"mbedTLS archive ready  -> {archive}  ({archive.stat().st_size / 1024:.0f} KB)")
    return archive


# ---- main ------------------------------------------------------------------
#
# Standalone entry point: render version.h and (re)build the mbedTLS
# archive. The Tk exe itself is built by tasks.lua, which calls the
# same two helpers; this main() exists so the prerequisites can be primed
# (or cache-warmed) from the command line.


def main() -> None:
    BUILD.mkdir(exist_ok=True)
    version = read_version()
    write_version_header(BUILD, version)
    log(f"Version {version} (from VERSION)  ->  {BUILD / 'version.h'}")
    gcc = find_tool("gcc")
    archive = build_mbedtls_archive(gcc)
    log(f"Prerequisites ready: {archive}")


if __name__ == "__main__":
    main()
